// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Check from '../src/commands/check.js'
import Convert from '../src/commands/convert.js'
import Deploy from '../src/commands/deploy.js'
import Exec from '../src/commands/exec.js'
import Find from '../src/commands/find.js'
import FromJson from '../src/commands/from-json.js'
import Hello from '../src/commands/hello.js'
import Log from '../src/commands/log.js'
import Ps from '../src/commands/ps.js'
import Run from '../src/commands/run.js'
import ToIr from '../src/commands/to-ir.js'
import ToJson from '../src/commands/to-json.js'
import Tui from '../src/commands/tui.js'
import Undeploy from '../src/commands/undeploy.js'
import VolumePath from '../src/commands/volume-path.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['check', 'convert', 'deploy', 'exec', 'find', 'from-json', 'hello', 'log', 'ps', 'run', 'to-ir', 'to-json', 'tui', 'undeploy', 'volume-path'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'check': Check,
  'convert': Convert,
  'deploy': Deploy,
  'exec': Exec,
  'find': Find,
  'from-json': FromJson,
  'hello': Hello,
  'log': Log,
  'ps': Ps,
  'run': Run,
  'to-ir': ToIr,
  'to-json': ToJson,
  'tui': Tui,
  'undeploy': Undeploy,
  'volume-path': VolumePath
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'check': {
      name: 'check',
      description: 'Check a compose file for potential issues',
      path: './src/commands/check'
    },
  'convert': {
      name: 'convert',
      description: 'Convert between Compose and Quadlet formats',
      commands: [
        {
          name: 'compose-to-quadlet',
          description: 'Convert a Docker Compose file to Quadlet unit file(s)',
          options: {
            'output': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Output directory (default: deploy/ next to compose file)', short: 'o', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'sops': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Use sops to decrypt file-based secrets in justfile recipes', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":918,"end":923,"loc":{"start":{"line":23,"column":26,"index":918},"end":{"line":23,"column":31,"index":923}},"value":false}}]}, validator: '(val) => true' },
            'build': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate build recipes for services with build contexts', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1077,"end":1082,"loc":{"start":{"line":29,"column":26,"index":1077},"end":{"line":29,"column":31,"index":1082}},"value":false}}]}, validator: '(val) => true' },
            'start-port': { type: 'z.coerce.number.optional', required: false, hasDefault: false, description: 'Starting host port for scaled instances', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'no-pod': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate standalone containers instead of pods for scaled services', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1385,"end":1390,"loc":{"start":{"line":41,"column":26,"index":1385},"end":{"line":41,"column":31,"index":1390}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/convert/compose-to-quadlet'
        },
        {
          name: 'quadlet-to-compose',
          description: 'Convert a Quadlet unit file to Docker Compose YAML',
          options: {
            'service': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Service name to use in the compose output', short: 's', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/convert/quadlet-to-compose'
        }
      ],
      path: './src/commands/convert'
    },
  'deploy': {
      name: 'deploy',
      description: 'Install quadlet units and start services',
      options: {
        'system': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Deploy system-wide instead of per-user', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1073,"end":1078,"loc":{"start":{"line":36,"column":26,"index":1073},"end":{"line":36,"column":31,"index":1078}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/deploy'
    },
  'exec': {
      name: 'exec',
      description: 'Execute a command in a running container by service name',
      options: {
        'project': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Filter by project name', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Allocate a TTY (default: true)', short: 'i', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":443,"end":447,"loc":{"start":{"line":14,"column":26,"index":443},"end":{"line":14,"column":30,"index":447}},"value":true}}]}, validator: '(val) => true' }
      },
      path: './src/commands/exec'
    },
  'find': {
      name: 'find',
      description: 'Find a running container by service name',
      options: {
        'project': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Filter by project name', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/find'
    },
  'from-json': {
      name: 'from-json',
      description: 'Convert JSON to other formats',
      commands: [
        {
          name: 'quadlet',
          description: 'Convert a JSON file to Quadlet unit format',
          path: './src/commands/from-json/quadlet'
        }
      ],
      path: './src/commands/from-json'
    },
  'hello': {
      name: 'hello',
      description: 'Say hello to someone',
      options: {
        'name': { type: 'z.string.default', required: true, hasDefault: true, default: "World", description: 'Name to greet', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"World"}]}, validator: '(val) => true' },
        'excited': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Add excitement!', short: 'e', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":364,"end":369,"loc":{"start":{"line":16,"column":26,"index":364},"end":{"line":16,"column":31,"index":369}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/hello'
    },
  'log': {
      name: 'log',
      description: 'Follow journald logs for a deployed project',
      options: {
        'system': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Use system scope instead of user', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":654,"end":659,"loc":{"start":{"line":24,"column":26,"index":654},"end":{"line":24,"column":31,"index":659}},"value":false}}]}, validator: '(val) => true' },
        'follow': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Follow log output (default: true)', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":774,"end":778,"loc":{"start":{"line":28,"column":26,"index":774},"end":{"line":28,"column":30,"index":778}},"value":true}}]}, validator: '(val) => true' }
      },
      path: './src/commands/log'
    },
  'ps': {
      name: 'ps',
      description: 'List running quadlet containers',
      options: {
        'all': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show all containers (including non-quadlet)', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2278,"end":2283,"loc":{"start":{"line":79,"column":26,"index":2278},"end":{"line":79,"column":31,"index":2283}},"value":false}}]}, validator: '(val) => true' },
        'project': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Filter by project name', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Output as JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2537,"end":2542,"loc":{"start":{"line":87,"column":26,"index":2537},"end":{"line":87,"column":31,"index":2542}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/ps'
    },
  'run': {
      name: 'run',
      description: 'Run a .container quadlet file via podman-compose',
      options: {
        'service': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Service name to use (default: derived from filename)', short: 's', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'detach': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Run in detached mode', short: 'd', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":541,"end":546,"loc":{"start":{"line":18,"column":26,"index":541},"end":{"line":18,"column":31,"index":546}},"value":false}}]}, validator: '(val) => true' },
        'rm': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Remove containers and volumes after stopping', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":678,"end":683,"loc":{"start":{"line":25,"column":26,"index":678},"end":{"line":25,"column":31,"index":683}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/run'
    },
  'to-ir': {
      name: 'to-ir',
      description: 'Convert JSON to intermediate representation',
      commands: [
        {
          name: 'quadlet',
          description: 'Convert QuadletData JSON to QuadletIR',
          options: {
            'pretty': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Pretty-print the JSON output', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":319,"end":323,"loc":{"start":{"line":10,"column":26,"index":319},"end":{"line":10,"column":30,"index":323}},"value":true}}]}, validator: '(val) => true' }
          },
          path: './src/commands/to-ir/quadlet'
        }
      ],
      path: './src/commands/to-ir'
    },
  'to-json': {
      name: 'to-json',
      description: 'Convert files to JSON',
      commands: [
        {
          name: 'quadlet',
          description: 'Convert a Quadlet unit file to JSON',
          options: {
            'pretty': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Pretty-print the JSON output', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":300,"end":304,"loc":{"start":{"line":10,"column":26,"index":300},"end":{"line":10,"column":30,"index":304}},"value":true}}]}, validator: '(val) => true' }
          },
          path: './src/commands/to-json/quadlet'
        },
        {
          name: 'compose',
          description: 'Convert a Docker Compose file to JSON',
          options: {
            'pretty': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Pretty-print the JSON output', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":308,"end":312,"loc":{"start":{"line":10,"column":26,"index":308},"end":{"line":10,"column":30,"index":312}},"value":true}}]}, validator: '(val) => true' },
            'validate': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Validate against the Compose specification schema', short: 'v', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":458,"end":462,"loc":{"start":{"line":17,"column":26,"index":458},"end":{"line":17,"column":30,"index":462}},"value":true}}]}, validator: '(val) => true' }
          },
          path: './src/commands/to-json/compose'
        }
      ],
      path: './src/commands/to-json'
    },
  'tui': {
      name: 'tui',
      description: 'Interactive file browser with live conversion preview',
      options: {
        'dir': { type: 'z.string.default', required: true, hasDefault: true, default: ".", description: 'Directory to browse', short: 'd', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"."}]}, validator: '(val) => true' }
      },
      path: './src/commands/tui'
    },
  'undeploy': {
      name: 'undeploy',
      description: 'Stop services, remove quadlet units, and reload systemd',
      options: {
        'system': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Undeploy system-wide instead of per-user', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1136,"end":1141,"loc":{"start":{"line":39,"column":26,"index":1136},"end":{"line":39,"column":31,"index":1141}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/undeploy'
    },
  'volume-path': {
      name: 'volume-path',
      description: 'Get the mountpoint of a volume by name, trying prefixed variants',
      options: {
        'project': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Project name to try as prefix', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/volume-path'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
